T 54 vrije feedback naamwoordstijl
pxldigital-s2it/internship-wordtool-2324-team2 pull request #34
Opened 2024-02-20 17:43 UTC by Bartvovke

Als er geen subcategories zijn, wordt er een FreeFeedbackInput component gerenderd. Dit component krijgt optionele props mee om het highlighten te regelen. In het FreeFeedbackInput onderaan worden deze niet meegegeven en wordt er niets gehighlight. 

Ik heb nog een paar verbeteringen in mijn hoofd, maar maak alvast deze PR. De verbeteringen kan ik ook in een ander ticket doen eventueel.

2024-02-22 07:37 UTC, svendp1988 commented on src/components/freefeedbackinput/FreeFeedbackInput.tsx
> +
Dit gedrag klopt niet. Als ge nu vrije feedback invoegt bij Naamwoordstijl, krijgt ge eerst uw vrije feedback 
bv: (Dit kan beter)
En dan op een nieuwe regel in het rood (Naamwoordstijl)

2024-02-22 07:39 UTC, svendp1988 requested changes
Het gedrag vn de vrije feedback bij naamwoordstijl klopt niet. Zie comment daar.

2024-02-22 10:35 UTC, PeterRenaertsPXL approved these changes

2024-02-22 10:51 UTC, svendp1988 commented on src/taskpane/office-document.ts
> +async function getInsertText(description: string, context: Word.RequestContext, category: Category, shortCode: string, freeFeedback: string) {
freeFeedback is niet optional, hier.

2024-02-22 10:51 UTC, svendp1988 commented on src/taskpane/office-document.ts
> +        const thirdToLastIndex = descriptionInsert.length - 2;
Dit kan toch naar boven:
`let descriptionInsert = `    let descriptionInsert = " (" + category.title +" - " + freeFeedback || description + ") ";`
Er van uit gaande dat als er freeFeedback wordt meegegeven de description er niet toe doet.

2024-02-22 10:51 UTC, svendp1988 commented on src/components/category/maincategory/CategoryComponent.tsx
> +                <FreeFeedbackInput categoryId={id} description={title} shortCode={code} />
Heeft die een shortCode nodig?

2024-02-22 10:53 UTC, Bartvovke commented on src/taskpane/office-document.ts
> +        const thirdToLastIndex = descriptionInsert.length - 2;
Nee, want de freeFeedback gaat meestal verschilllend zijn en dan gaat die dat nooit vinden. De ene keer is dat (Naamwoordstijl - freeFeedback) en de volgende keer (Naamwoordstijl - freeFeedback1) bv en dan gaat Naamwoordstijl nooit verkort worden. Die functionaliteit werkt hiermee ook niet goed, maar ben ik aan het fixen

2024-02-22 10:55 UTC, Bartvovke commented on src/components/category/maincategory/CategoryComponent.tsx
> +                <FreeFeedbackInput categoryId={id} description={title} shortCode={code} />
Het component misschien niet perse, maar er moet wel een shortcode meegegeven worden met de insertAndHightlighText functie en als die vanuit het component komt is die later makkelijker weg te filteren vermits dat dezelfde is als de code van de category en daar kan op getest worden

2024-02-22 11:43 UTC, svendp1988 commented on src/taskpane/office-document.ts
> +        const thirdToLastIndex = descriptionInsert.length - 2;
naamwoordstijl moet nooit verkort worden denkk

2024-02-22 11:44 UTC, svendp1988 commented on src/components/category/maincategory/CategoryComponent.tsx
> +                <FreeFeedbackInput categoryId={id} description={title} shortCode={code} />
is het niet beter om die dan optional te maken in de insertAndHighlightText functie?

2024-02-23 16:04 UTC, svendp1988 commented on src/taskpane/office-document.ts
> +        const thirdToLastIndex = descriptionInsert.length - 2;
Sorry, ik ga toch nog ff vervelend doen want voor mij is dat stukske code veel te complex en fragiel. Zou ge hier met die officeMock een test voor kunnen schrijven, aub?

2024-02-27 06:48 UTC, svendp1988 commented on src/taskpane/office-document.ts
> +/*import { getCategory } from "../middleware/modal/ModalMiddleware";
Deze file mag weg als die niet meer gebruikt wordt.

2024-02-28 17:26 UTC, merged